export {default as Home} from './Home'
export {default as Electric} from './Electric'
export {default as About} from './About'
export {default as Medicine} from './Medicine'
export {default as Contacts} from './Contacts'
export {default as Footer} from './Footer'
export {default as Slider} from './Slider'
export {default as ElectricSlider} from './ElectricSlider'